### ISSUE TITLE
Linked tutorial returns 404

### ISSUE THREAD

**Issue by davidrea** [rpoisel/cmake-unity-tutorial#1]
Visiting https://www.poisel.info/cmake-unity-integration/ responds with a 404 error; maybe migrate content to an associated GitHub gist?

**Comment by rpoisel** [comment]
Sorry for the inconvenience, the article has moved here: https://www.poisel.info/blog/2019/07/15/cmake-unity-integration/

**Comment by davidrea** [comment]
Thanks so much!

**Comment by TS-rrojas** [comment]
Both Links above do not work. Has the article been moved again?

**Comment by rpoisel** [comment]
Sorry for the inconvenience, it has been moved here: https://poisel.info/posts/2019-07-15-cmake-unity-integration/
